import { v4 as uuidv4 } from 'uuid';

import { ADMIN_POSITION, ADMIN_ROLE, ADMIN_TEAM } from './admin.js';

export const ABOUT_SNOROSE = `스노로즈는 숙명인이 직접 운영하는 숙명인만을 위한 커뮤니티입니다.

2007년 8월 15일 처음 문을 연 이후 현재까지 숙명인들의 사랑을 받으며, ‘숙명인만을 위한 캠퍼스 너머의 공간’이 되고자 각종 교내외 정보를 공유하고 서로의 일상을 진솔하게 주고받는 나눔과 소통의 장으로 꾸준히 성장해 왔습니다. 지금껏 그래왔듯 앞으로도 스노로즈는 오직 숙명인을 위해, 그리고 숙명인에 의해 투명하게 운영될 것이며, 하나된 숙명을 위해 튼튼한 다리가 될 것임을 약속합니다.

스노로즈는 모든 숙명인에게 열려 있습니다.
숙명여대 유일 커뮤니티, 스노로즈의 문을 두드려주세요.

문의메일 : snorose1906@gmail.com
카카오톡 문의 창구: (http://pf.kakao.com/_Xmhxhn)`;

export const SNOROSE_HISTORY = Object.freeze([
  '스노로즈 1.0(블랙로즈) - 07.08.15 오픈',
  '스노로즈 2.0(블루로즈) - 08.01.01 오픈',
  '스노로즈 3.0(화이트로즈) - 09.11.01 오픈',
  '스노로즈 4.0 - 15.11.12 오픈',
  '스노로즈 5.0 - 18.09.08 오픈',
  '스노로즈 6.0 - 24.10.12 오픈',
]);

export const SNOROSE_MEMBERSHIP_LEVEL = Object.freeze([
  '준회원: 최초 가입 시 수여되는 등급으로, 숙명인 인증이 완료되지 않은 회원입니다. 일부 게시판 및 기능만 이용할 수 있습니다.',
  '정회원: 숙명인 인증을 완료한 회원입니다. 모든 게시판 및 기능을 이용할 수 있습니다.',
  '리자: 스노로즈의 관리자입니다.',
  '공식 계정: 총학생회, 졸업준비위원회 등 교내 공식 기구 전용 등급입니다.',
  '블랙리스트: 강등된 회원입니다. 강등 기간이 종료되면 준회원으로 조정됩니다.',
]);

export const HALL_OF_FAME_ADMINS = Object.freeze([
  {
    id: uuidv4(),
    nickname: '원조리자',
    role: undefined,
    team: undefined,
    position: undefined,
    studentInformation: undefined,
  },
  {
    id: uuidv4(),
    nickname: '까만눈송이',
    role: undefined,
    team: undefined,
    position: undefined,
    studentInformation: undefined,
  },
  {
    id: uuidv4(),
    nickname: '닷닷',
    role: undefined,
    team: undefined,
    position: undefined,
    studentInformation: undefined,
  },
  {
    id: uuidv4(),
    nickname: '가필드',
    role: undefined,
    team: undefined,
    position: undefined,
    studentInformation: undefined,
  },
  {
    id: uuidv4(),
    nickname: '잉여잉여',
    role: undefined,
    team: undefined,
    position: undefined,
    studentInformation: undefined,
  },
  {
    id: uuidv4(),
    nickname: '삶은계란',
    role: undefined,
    team: undefined,
    position: undefined,
    studentInformation: undefined,
  },
  {
    id: uuidv4(),
    nickname: '돌핀포스',
    role: undefined,
    team: undefined,
    position: undefined,
    studentInformation: undefined,
  },
  {
    id: uuidv4(),
    nickname: '아카리☆',
    role: undefined,
    team: undefined,
    position: undefined,
    studentInformation: undefined,
  },
  {
    id: uuidv4(),
    nickname: 'nodame',
    role: undefined,
    team: undefined,
    position: undefined,
    studentInformation: undefined,
  },
  {
    id: uuidv4(),
    nickname: '샤인',
    role: undefined,
    team: undefined,
    position: undefined,
    studentInformation: undefined,
  },
  {
    id: uuidv4(),
    nickname: 'ringo89',
    role: undefined,
    team: undefined,
    position: undefined,
    studentInformation: undefined,
  },
  {
    id: uuidv4(),
    nickname: '박죠신',
    role: undefined,
    team: undefined,
    position: undefined,
    studentInformation: undefined,
  },
  {
    id: uuidv4(),
    nickname: 'cym_',
    role: undefined,
    team: undefined,
    position: undefined,
    studentInformation: undefined,
  },
  {
    id: uuidv4(),
    nickname: '부러운11학번',
    role: undefined,
    team: undefined,
    position: undefined,
    studentInformation: undefined,
  },
  {
    id: uuidv4(),
    nickname: '풀순이',
    role: undefined,
    team: undefined,
    position: undefined,
    studentInformation: undefined,
  },
  {
    id: uuidv4(),
    nickname: '꺼삐딴리',
    role: undefined,
    team: undefined,
    position: undefined,
    studentInformation: undefined,
  },
  {
    id: uuidv4(),
    nickname: '순두부',
    role: undefined,
    team: undefined,
    position: undefined,
    studentInformation: undefined,
  },
  {
    id: uuidv4(),
    nickname: '로즈',
    role: undefined,
    team: undefined,
    position: undefined,
    studentInformation: undefined,
  },
  {
    id: uuidv4(),
    nickname: '숙대유나킴',
    role: undefined,
    team: undefined,
    position: undefined,
    studentInformation: undefined,
  },
  {
    id: uuidv4(),
    nickname: '술이들어간다',
    role: undefined,
    team: undefined,
    position: undefined,
    studentInformation: undefined,
  },
  {
    id: uuidv4(),
    nickname: '제왕타마마',
    role: undefined,
    team: undefined,
    position: undefined,
    studentInformation: undefined,
  },
  {
    id: uuidv4(),
    nickname: '토갱이',
    role: undefined,
    team: undefined,
    position: undefined,
    studentInformation: undefined,
  },
  {
    id: uuidv4(),
    nickname: '한화가을야구',
    role: undefined,
    team: undefined,
    position: undefined,
    studentInformation: undefined,
  },
  {
    id: uuidv4(),
    nickname: '빵수니',
    role: undefined,
    team: undefined,
    position: undefined,
    studentInformation: undefined,
  },
  {
    id: uuidv4(),
    nickname: '홍삼이',
    role: undefined,
    team: undefined,
    position: undefined,
    studentInformation: undefined,
  },
  {
    id: uuidv4(),
    nickname: '로즈세스코',
    role: undefined,
    team: undefined,
    position: undefined,
    studentInformation: undefined,
  },
  {
    id: uuidv4(),
    nickname: '후다닥',
    role: undefined,
    team: undefined,
    position: undefined,
    studentInformation: undefined,
  },
  {
    id: uuidv4(),
    nickname: '김종현',
    role: undefined,
    team: undefined,
    position: undefined,
    studentInformation: undefined,
  },
  {
    id: uuidv4(),
    nickname: '달물결',
    role: undefined,
    team: undefined,
    position: undefined,
    studentInformation: undefined,
  },
  {
    id: uuidv4(),
    nickname: '꾸꾸까까깍',
    role: undefined,
    team: undefined,
    position: undefined,
    studentInformation: undefined,
  },
  {
    id: uuidv4(),
    nickname: '법도지박령',
    role: undefined,
    team: undefined,
    position: undefined,
    studentInformation: undefined,
  },
  {
    id: uuidv4(),
    nickname: '난나나나',
    role: undefined,
    team: undefined,
    position: undefined,
    studentInformation: undefined,
  },
  {
    id: uuidv4(),
    nickname: '규루루',
    role: undefined,
    team: undefined,
    position: undefined,
    studentInformation: undefined,
  },
  {
    id: uuidv4(),
    nickname: '숙대화석',
    role: undefined,
    team: undefined,
    position: undefined,
    studentInformation: undefined,
  },
  {
    id: uuidv4(),
    nickname: '숙대미피',
    role: undefined,
    team: undefined,
    position: undefined,
    studentInformation: undefined,
  },
  {
    id: uuidv4(),
    nickname: '눈송이',
    role: undefined,
    team: undefined,
    position: undefined,
    studentInformation: undefined,
  },
  {
    id: uuidv4(),
    nickname: 'Q__',
    role: undefined,
    team: undefined,
    position: undefined,
    studentInformation: undefined,
  },
  {
    id: uuidv4(),
    nickname: '숙램덩크',
    role: undefined,
    team: undefined,
    position: undefined,
    studentInformation: undefined,
  },
  {
    id: uuidv4(),
    nickname: '눈송더쿠',
    role: undefined,
    team: undefined,
    position: undefined,
    studentInformation: undefined,
  },
  {
    id: uuidv4(),
    nickname: '분홍스트라이프',
    role: undefined,
    team: undefined,
    position: undefined,
    studentInformation: undefined,
  },
  {
    id: uuidv4(),
    nickname: '눈뚱이',
    role: ADMIN_ROLE.president,
    team: [ADMIN_TEAM.operationsPlanning],
    position: undefined,
    studentInformation: undefined,
  },
  {
    id: uuidv4(),
    nickname: '가을',
    role: undefined,
    team: [ADMIN_TEAM.operationsPlanning],
    position: undefined,
    studentInformation: undefined,
  },

  {
    id: uuidv4(),
    nickname: '퀴디치',
    role: undefined,
    team: [ADMIN_TEAM.operationsPlanning],
    position: undefined,
    studentInformation: undefined,
  },
  {
    id: uuidv4(),
    nickname: '마그네슘',
    role: ADMIN_ROLE.treasurer,
    team: undefined,
    position: undefined,
    studentInformation: undefined,
  },
  {
    id: uuidv4(),
    nickname: '온니유',
    role: ADMIN_ROLE.vicePresident,
    team: [ADMIN_TEAM.design],
    position: undefined,
    studentInformation: undefined,
  },
  {
    id: uuidv4(),
    nickname: '퀸송이',
    role: ADMIN_ROLE.president,
    team: [ADMIN_TEAM.design],
    position: undefined,
    studentInformation: undefined,
  },
  {
    id: uuidv4(),
    nickname: '마라탕',
    role: undefined,
    team: [ADMIN_TEAM.operationsPlanning],
    position: undefined,
    studentInformation: undefined,
  },
  {
    id: uuidv4(),
    nickname: 'HEE',
    role: undefined,
    team: [ADMIN_TEAM.operationsPlanning],
    position: undefined,
    studentInformation: undefined,
  },
  {
    id: uuidv4(),
    nickname: '숙프로',
    role: undefined,
    team: [ADMIN_TEAM.operationsPlanning],
    position: undefined,
    studentInformation: undefined,
  },
  {
    id: uuidv4(),
    nickname: '010',
    role: undefined,
    team: [ADMIN_TEAM.operationsPlanning],
    position: undefined,
    studentInformation: undefined,
  },
  {
    id: uuidv4(),
    nickname: '니니',
    role: undefined,
    team: [ADMIN_TEAM.development],
    position: undefined,
    studentInformation: undefined,
  },
  {
    id: uuidv4(),
    nickname: '빙글빙글',
    role: ADMIN_ROLE.treasurer,
    team: [ADMIN_TEAM.operationsPlanning],
    position: undefined,
    studentInformation: undefined,
  },
  {
    id: uuidv4(),
    nickname: 'apoptoxis',
    role: undefined,
    team: [ADMIN_TEAM.development],
    position: undefined,
    studentInformation: undefined,
  },
  {
    id: uuidv4(),
    nickname: '빨간무당벌레',
    role: undefined,
    team: [ADMIN_TEAM.development],
    position: undefined,
    studentInformation: undefined,
  },
  {
    id: uuidv4(),
    nickname: 'f1re7h',
    role: undefined,
    team: [ADMIN_TEAM.operationsPlanning],
    position: undefined,
    studentInformation: undefined,
  },
  {
    id: uuidv4(),
    nickname: '나루미',
    role: undefined,
    team: [ADMIN_TEAM.operationsPlanning],
    position: undefined,
    studentInformation: undefined,
  },
  {
    id: uuidv4(),
    nickname: '눈떠',
    role: undefined,
    team: [ADMIN_TEAM.development],
    position: undefined,
    studentInformation: undefined,
  },
  {
    id: uuidv4(),
    nickname: '코코송이',
    role: undefined,
    team: [ADMIN_TEAM.development],
    position: undefined,
    studentInformation: undefined,
  },
  {
    id: uuidv4(),
    nickname: '지선',
    role: undefined,
    team: [ADMIN_TEAM.development],
    position: undefined,
    studentInformation: undefined,
  },
  {
    id: uuidv4(),
    nickname: '새송송',
    role: undefined,
    team: [ADMIN_TEAM.operationsPlanning],
    position: undefined,
    studentInformation: undefined,
  },
  {
    id: uuidv4(),
    nickname: '숙명의길',
    role: ADMIN_ROLE.president,
    team: [ADMIN_TEAM.operationsPlanning],
    position: undefined,
    studentInformation: '(경영학부 14 김아란)',
  },
  {
    id: uuidv4(),
    nickname: 'silver',
    role: ADMIN_ROLE.vicePresident,
    team: [ADMIN_TEAM.operationsPlanning],
    position: undefined,
    studentInformation: '(영어영문학부 16 은선민)',
  },
  {
    id: uuidv4(),
    nickname: '파이',
    role: undefined,
    team: [ADMIN_TEAM.development],
    position: [ADMIN_POSITION.backEnd, ADMIN_POSITION.infra],
    studentInformation: '(시각영상디자인과 17 이지수)',
  },
  {
    id: uuidv4(),
    nickname: 'milkyway',
    role: ADMIN_ROLE.vicePresident,
    team: [ADMIN_TEAM.development],
    position: [ADMIN_POSITION.backEnd],
    studentInformation: '(IT공학전공 19 김민지)',
  },
  {
    id: uuidv4(),
    nickname: 'Alicey',
    role: ADMIN_ROLE.president,
    team: [ADMIN_TEAM.operationsPlanning, ADMIN_TEAM.development],
    position: [ADMIN_POSITION.backEnd],
    studentInformation: '(생명시스템학부 18 윤종화)',
  },
  {
    id: uuidv4(),
    nickname: '과제가날죽여',
    role: undefined,
    team: [ADMIN_TEAM.development],
    position: [ADMIN_POSITION.backEnd],
    studentInformation: '(컴퓨터과학전공 17 김민정)',
  },
  {
    id: uuidv4(),
    nickname: '눈송이',
    role: undefined,
    team: [ADMIN_TEAM.development],
    position: [ADMIN_POSITION.backEnd],
    studentInformation: '(컴퓨터과학전공 20 조세영)',
  },
  {
    id: uuidv4(),
    nickname: '치아바타',
    role: undefined,
    team: [ADMIN_TEAM.development],
    position: [ADMIN_POSITION.backEnd],
    studentInformation: '(컴퓨터과학전공 22 문채일)',
  },
  {
    id: uuidv4(),
    nickname: '조욘',
    role: undefined,
    team: [ADMIN_TEAM.development],
    position: [ADMIN_POSITION.backEnd],
    studentInformation: '(IT공학전공 20 조용은)',
  },
  {
    id: uuidv4(),
    nickname: '수야',
    role: undefined,
    team: [ADMIN_TEAM.development],
    position: [ADMIN_POSITION.frontEnd],
    studentInformation: '(컴퓨터과학전공 20 홍희수)',
  },
  {
    id: uuidv4(),
    nickname: 'draud',
    role: undefined,
    team: [ADMIN_TEAM.development],
    position: [ADMIN_POSITION.infra],
    studentInformation: '(IT공학전공 20 김민지)',
  },
  {
    id: uuidv4(),
    nickname: '따꿍',
    role: undefined,
    team: [ADMIN_TEAM.development],
    position: [ADMIN_POSITION.frontEnd],
    studentInformation: '(컴퓨터과학전공 22 정민주)',
  },
  {
    id: uuidv4(),
    nickname: '돌굴러가용',
    role: undefined,
    team: [ADMIN_TEAM.operationsPlanning],
    position: undefined,
    studentInformation: '(경영학부 23 채현지)',
  },
  {
    id: uuidv4(),
    nickname: '부메랑',
    role: undefined,
    team: [ADMIN_TEAM.development],
    position: [ADMIN_POSITION.frontEnd],
    studentInformation: '(컴퓨터과학전공 20 송희원)',
  },
  {
    id: uuidv4(),
    nickname: '뇽구',
    role: undefined,
    team: [ADMIN_TEAM.development],
    position: [ADMIN_POSITION.frontEnd],
    studentInformation: '(컴퓨터과학전공 22 김준희)',
  },
  {
    id: uuidv4(),
    nickname: '칙촉',
    role: undefined,
    team: [ADMIN_TEAM.operationsPlanning, ADMIN_TEAM.development],
    position: [ADMIN_POSITION.frontEnd],
    studentInformation: '(컴퓨터과학전공 21 류미성)',
  },
  {
    id: uuidv4(),
    nickname: '보라송이',
    role: undefined,
    team: [ADMIN_TEAM.design],
    position: undefined,
    studentInformation: '(공예과 21 김수진)',
  },
  {
    id: uuidv4(),
    nickname: '더엉',
    role: undefined,
    team: [ADMIN_TEAM.design],
    position: undefined,
    studentInformation: '(산업디자인과 22 문서영)',
  },
  {
    id: uuidv4(),
    nickname: '응앵응',
    role: undefined,
    team: [ADMIN_TEAM.operationsPlanning],
    position: undefined,
    studentInformation: '(컴퓨터과학전공 22 김나경)',
  },
  {
    id: uuidv4(),
    nickname: '쭉쭉이',
    role: undefined,
    team: [ADMIN_TEAM.operationsPlanning],
    position: undefined,
    studentInformation: '(경영학부 23 민규원)',
  },
  {
    id: uuidv4(),
    nickname: '파랭이송',
    role: undefined,
    team: [ADMIN_TEAM.operationsPlanning],
    position: undefined,
    studentInformation: '(경영학부 24 양하은)',
  },
  {
    id: uuidv4(),
    nickname: 'lineya',
    role: undefined,
    team: [ADMIN_TEAM.operationsPlanning],
    position: undefined,
    studentInformation: '(경영학부 23 이채린)',
  },
  {
    id: uuidv4(),
    nickname: 'yesmynamein',
    role: undefined,
    team: [ADMIN_TEAM.operationsPlanning],
    position: undefined,
    studentInformation: '(인공지능공학부 24 조예인)',
  },
  {
    id: uuidv4(),
    nickname: '로즈1',
    role: undefined,
    team: [ADMIN_TEAM.operationsPlanning],
    position: undefined,
    studentInformation: '(정치외교학과 22 강영주)',
  },
  {
    id: uuidv4(),
    nickname: '무민동생',
    role: undefined,
    team: [ADMIN_TEAM.operationsPlanning],
    position: undefined,
    studentInformation: '(홍보광고학과 24 김연수)',
  },
  {
    id: uuidv4(),
    nickname: 'dlwjd',
    role: undefined,
    team: [ADMIN_TEAM.operationsPlanning],
    position: undefined,
    studentInformation: '(경제학부 21 이효정)',
  },
  {
    id: uuidv4(),
    nickname: '세린이',
    role: undefined,
    team: [ADMIN_TEAM.operationsPlanning],
    position: undefined,
    studentInformation: '(경영학부 24 김우림)',
  },
  {
    id: uuidv4(),
    nickname: 'kiahvn_',
    role: undefined,
    team: [ADMIN_TEAM.operationsPlanning],
    position: undefined,
    studentInformation: '(수학과 22 전수빈)',
  },
  {
    id: uuidv4(),
    nickname: '이부',
    role: undefined,
    team: [ADMIN_TEAM.development],
    position: [ADMIN_POSITION.frontEnd],
    studentInformation: '(소프트웨어융합전공 18 김선진)',
  },
  {
    id: uuidv4(),
    nickname: '화산송이',
    role: undefined,
    team: [ADMIN_TEAM.development],
    position: [ADMIN_POSITION.frontEnd],
    studentInformation: '(컴퓨터과학전공 20 장아현)',
  },
  {
    id: uuidv4(),
    nickname: '그냥에',
    role: undefined,
    team: [ADMIN_TEAM.development],
    position: [ADMIN_POSITION.backEnd],
    studentInformation: '(한국어문학부 18 김경민)',
  },
  {
    id: uuidv4(),
    nickname: '배고프다이어터',
    role: undefined,
    team: [ADMIN_TEAM.development],
    position: [ADMIN_POSITION.backEnd],
    studentInformation: '(IT공학전공 22 백지현)',
  },
  {
    id: uuidv4(),
    nickname: '신송이',
    role: undefined,
    team: [ADMIN_TEAM.development],
    position: [ADMIN_POSITION.backEnd],
    studentInformation: '(컴퓨터과학전공 20 신진영)',
  },
  {
    id: uuidv4(),
    nickname: 'fjdksla',
    role: undefined,
    team: [ADMIN_TEAM.development],
    position: [ADMIN_POSITION.backEnd],
    studentInformation: '(IT공학전공 21 오수진)',
  },
  {
    id: uuidv4(),
    nickname: 'Hsss',
    role: undefined,
    team: [ADMIN_TEAM.development],
    position: [ADMIN_POSITION.backEnd],
    studentInformation: '(데이터사이언스전공 23 윤현서)',
  },
  {
    id: uuidv4(),
    nickname: 'oceanwave',
    role: undefined,
    team: [ADMIN_TEAM.development],
    position: [ADMIN_POSITION.backEnd],
    studentInformation: '(소프트웨어융합전공 21 이서현)',
  },
  {
    id: uuidv4(),
    nickname: '피스탸',
    role: undefined,
    team: [ADMIN_TEAM.development],
    position: [ADMIN_POSITION.backEnd],
    studentInformation: '(IT공학전공 19 이예림)',
  },
  {
    id: uuidv4(),
    nickname: '김첨지의설렁탕',
    role: undefined,
    team: [ADMIN_TEAM.development],
    position: [ADMIN_POSITION.infra],
    studentInformation: '(인공지능공학부 23 이채영)',
  },
  {
    id: uuidv4(),
    nickname: 'yj9139',
    role: undefined,
    team: [ADMIN_TEAM.development],
    position: [ADMIN_POSITION.infra],
    studentInformation: '(경제학부 19 최유정)',
  },
  {
    id: uuidv4(),
    nickname: '순두지스카파',
    role: undefined,
    team: [ADMIN_TEAM.development],
    position: [ADMIN_POSITION.infra],
    studentInformation: '(컴퓨터과학전공 21 최은소)',
  },
  {
    id: uuidv4(),
    nickname: '지인',
    role: undefined,
    team: [ADMIN_TEAM.design],
    position: undefined,
    studentInformation: '(산업디자인과 22 김지인)',
  },
]);
