export type BoardKey =
  | 'FIRST-SNOW'
  | 'LARGE-SNOW'
  | 'PERMANENT-SNOW'
  | 'BESOOKT'
  | 'EVENT'
  | 'EXAM-REVIEW'
  | 'STUDENT-COUNCIL'
  | 'GRADUATION-PREPARATION'
  | 'FINANCE-AUDIT'
  | 'NOTICE';
