export const REPORT_COMMENT_REASON_LIST = [
  {
    reportType: 'COMMENT_PERSONAL_ABUSE',
    iconId: 'comment-exclamation-question-mark',
    label: '특정인에 대한 욕설 및 비하',
    width: 20,
    height: 20,
  },
  {
    reportType: 'COMMENT_COMMERCIAL_AD',
    iconId: 'dollar-circle',
    label: '상업적 광고 및 판매',
    width: 20,
    height: 20,
  },
  {
    reportType: 'COMMENT_PRIVACY_VIOLATION',
    iconId: 'x-shield',
    label: '개인정보 유출',
    width: 18,
    height: 20,
  },
  {
    reportType: 'COMMENT_INCITEMENT_DIVISION',
    iconId: 'traffic-cone',
    label: '선동 및 분란 유발',
    width: 20,
    height: 20,
  },
  {
    reportType: 'COMMENT_ADULT_CONTENT',
    iconId: 'hand-stop',
    label: '음란물 / 불건전한 만남 및 대화',
    width: 20,
    height: 22,
  },
  {
    reportType: 'COMMENT_SPAM',
    iconId: 'list-x-circle',
    label: '스팸 / 무성의한 댓글',
    width: 20,
    height: 16,
  },
  {
    reportType: 'COMMENT_OTHER',
    iconId: 'null',
    label: '기타',
    width: 20,
    height: 20,
  },
];
